"""OpenPharmaStability — ICH Q1E-inspired stability analysis toolkit (v0.3)."""

from .contracts import (
    BQLSummary,
    CONFIDENCE,
    DISCLAIMER,
    POOLABILITY_ALPHA,
    REQUIRED_COLUMNS,
    AttributeMetadata,
    AttributeResult,
    AttributeRole,
    CrossingResult,
    CrossingStatus,
    DataQualityIssue,
    DataQualityReport,
    Direction,
    DiagnosticsResult,
    FitResult,
    IssueSeverity,
    ModelKind,
    MultiAttributeResult,
    Poolability,
    PoolabilityResult,
    StabilityResult,
    TransformAssessment,
    TransformCandidate,
    ValidatedData,
)
from .api import (
    analyze_and_artifact,
    analyze_csv,
    analyze_multi,
    analyze_path,
    analyze_xlsx,
    make_artifact,
)

__version__ = "0.6.0"

__all__ = [
    "BQLSummary",
    "CONFIDENCE",
    "DISCLAIMER",
    "POOLABILITY_ALPHA",
    "REQUIRED_COLUMNS",
    "AttributeMetadata",
    "AttributeResult",
    "AttributeRole",
    "CrossingResult",
    "CrossingStatus",
    "DataQualityIssue",
    "DataQualityReport",
    "Direction",
    "DiagnosticsResult",
    "FitResult",
    "IssueSeverity",
    "ModelKind",
    "MultiAttributeResult",
    "Poolability",
    "PoolabilityResult",
    "StabilityResult",
    "TransformAssessment",
    "TransformCandidate",
    "ValidatedData",
    # v0.6.0 thin programmatic API
    "analyze_csv",
    "analyze_xlsx",
    "analyze_path",
    "analyze_multi",
    "make_artifact",
    "analyze_and_artifact",
    "__version__",
]
