"""OpenPharmaStability — ICH Q1E-inspired stability analysis toolkit."""

from .contracts import (
    BQLSummary,
    CONFIDENCE,
    DISCLAIMER,
    POOLABILITY_ALPHA,
    REQUIRED_COLUMNS,
    ArrheniusShelfLife,
    AttributeMetadata,
    AttributeResult,
    AttributeRole,
    CrossingResult,
    CrossingStatus,
    DataQualityIssue,
    DataQualityReport,
    Direction,
    DiagnosticsResult,
    FitResult,
    IssueSeverity,
    ModelKind,
    MultiAttributeResult,
    Poolability,
    PoolabilityResult,
    StabilityResult,
    TransformAssessment,
    TransformCandidate,
    ValidatedData,
)
from .regulatory.profile import (
    DEFAULT_PROFILE,
    GuidanceProfile,
    PROFILES,
    Q1AE,
    Q1_CONSOLIDATED_DRAFT,
    resolve_profile,
)
from .api import (
    analyze_and_artifact,
    analyze_csv,
    analyze_multi,
    analyze_path,
    analyze_xlsx,
    compute_sensitivity_for,
    make_artifact,
    predict_arrhenius_shelf_life_for,
)

__version__ = "0.10.0"

__all__ = [
    "BQLSummary",
    "CONFIDENCE",
    "DISCLAIMER",
    "POOLABILITY_ALPHA",
    "REQUIRED_COLUMNS",
    "ArrheniusShelfLife",
    "AttributeMetadata",
    "AttributeResult",
    "AttributeRole",
    "CrossingResult",
    "CrossingStatus",
    "DataQualityIssue",
    "DataQualityReport",
    "Direction",
    "DiagnosticsResult",
    "FitResult",
    "IssueSeverity",
    "ModelKind",
    "MultiAttributeResult",
    "Poolability",
    "PoolabilityResult",
    "StabilityResult",
    "TransformAssessment",
    "TransformCandidate",
    "ValidatedData",
    "GuidanceProfile",
    "Q1AE",
    "Q1_CONSOLIDATED_DRAFT",
    "DEFAULT_PROFILE",
    "PROFILES",
    "resolve_profile",
    "analyze_csv",
    "analyze_xlsx",
    "analyze_path",
    "analyze_multi",
    "make_artifact",
    "analyze_and_artifact",
    "compute_sensitivity_for",
    "predict_arrhenius_shelf_life_for",
    "__version__",
]
